running:
  covariance: default
  score_threshold: 0.5
  max_age_since_update: 4
  min_hits_to_birth: 2
  match_type: bipartite
  asso: iou
  has_velo: false
  motion_model: kf
  asso_thres:
    iou: 0.5 # (1-threshold)

redundancy:
  mode: mm
  max_redundancy_age: 3
  det_score_threshold: 
    iou: 0.1
  det_dist_threshold: 
    iou: 0.2 # threshold